name: Create & Publish Docker Image

on:
  push:
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log In to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: pnpm install
      
      # - name: Build the Prod Docker Image
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     npm run docker:build:push --tag=$(echo ${GITHUB_REF_NAME:1})
      - run: |
          echo github.ref
      - run: |
          echo $(echo ${GITHUB_REF_NAME:1})
      - name: Build the Beta Docker Image
        if: github.ref != 'refs/heads/main'
        run: |
          TAG=${GITHUB_REF_NAME:1} pnpm run docker:build-beta:push
      
        
